services:
  - type: web
    name: inventory-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://inventorymanagementsystem-latest-fri0.onrender.com/api
    region: oregon
    healthCheckPath: /
    autoDeploy: true
